from collections import deque
mydq =deque([10,11,12,13])
print(mydq)
mydq.appendleft(9)
print(mydq)
mydq.append(14)
print(mydq)
print(mydq.popleft())
print(mydq)
print(mydq.pop())
print(mydq)
